- hosts: win

  tasks:


  - name: new variable with current date time
    set_fact: temp="{{lookup('pipe','date \"+%Y-%m-%d\"')}}"
#  - name: print variable
#    debug: msg="Current date and time is {{temp}}"

  - name: new variable with current date time
    set_fact: aysha="c:\source\{{lookup('pipe','date \"+%Y-%m-%d\"')}}_20.txt"

  - name: print variable
    debug: msg="file name {{aysha}}"


  - name: get mtime from c:\source\file
    win_stat:
      path: "{{ aysha }}"
    register: st

  #sintaxe correta para ver todos os parametros
  - name: print mtime
    debug:
      msg: "{{ st.stat.lastwritetime }}"
