---
- hosts: win

  tasks:

  - name: Check Themes
    win_service:
      name: Themes
    register: result
    failed_when: " result.state != 'running'"
#      ignore_errors: yes
  - mail:
    host: smtp.gmail.com
    port: 587
    username: hiratapqd@gmail.com
    password: kozevingqstzgtsb
    to: John Smith <john.smith@example.com>
    subject: Ansible-report
    body: 'System {{ result.state }} has been successfully provisioned.'
  delegate_to: localhost

  - debug: msg="{{result.state}}"

#  - debug: msg="running"
#    when: result.state is not defined or result.name is not defined
