---
- hosts: win

  tasks:

  - name: Check Themes
    win_service:
      name: Themes
    register: result
    failed_when: " result.state != 'running'"
    ignore_errors: yes

  - name: Check Power
    win_service:
      name: Power
    register: result1
    failed_when: " result.state != 'running'"
    ignore_errors: yes

  - name: Check SNMP trap
    win_service:
      name: SNMP trap
    register: result2
#    failed_when: " result.state != 'stopped'"
    ignore_errors: yes

  - name: result
    debug:
      msg: "[INFO] Service Theme is running"
    when: result|sucess

  - name: result1
    debug:
      msg: "[INFO] Service Powwer is running"
    when: result1|sucess

  - name: result2
    debug:
      msg: "[INFO] Service SNMP trap is stopped result.state"
    when: result2|sucess

  - fail:
      msg: "[ERROR] Service Theme NOT running"
    when: result|failed

  - fail:
      msg: "[ERROR] Service Theme NOT running"
    when: result1|failed

  - fail:
      msg: "[ERROR] Service Theme NOT stopped result.state"
    when: result2|failed
