---

- hosts: win

  tasks:

    - name: Look for folders on host
      win_find:
        paths:
          - C:\target
          - c:\source
          - c:\rundeck
        age: 10m
        file_type: directory
        recurse: yes
      register: folders_found

    - name: get folder paths
      debug:
        msg: "{{ item.path }}"
      with_items:
        - "{{ folders_found.files }}"

    - name: deleting folders
      win_file:
        #path: c:\target\folder4
        path: "{{ item.path | basename }}"
#        args:
#          chdir: c:\target
        state: absent
      with_items:
        - "{{ folders_found.files }}"

## pega as informacoes que queremos
#    - name:
#      debug:
#        msg: "{{ apps_found.files }}"
